# Inherit from the common Open Source product configuration
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)

PRODUCT_NAME := omni_CRO_U00
PRODUCT_DEVICE := CRO_U00

PRODUCT_BRAND := HUAWEI
PRODUCT_MODEL := CRO-U00
PRODUCT_MANUFACTURER := HUAWEI

#PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
#    ro.build.user=build \
#    ro.build.host=localhost

PRODUCT_BUILD_PROP_OVERRIDES += \
    OMNI_DEVICE="HWCRO-U6580M"

# Warning: Legacy build with CRO_U00
#PRODUCT_BUILD_PROP_OVERRIDES += \
#    TARGET_DEVICE="HWCRO-U6580M"

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRODUCT_NAME="CRO-U00"

PRODUCT_BUILD_PROP_OVERRIDES += \
    BUILD_ID="HUAWEICRO-U00" \
    BUILD_NUMBER="C10B122" \
    BUILD_DISPLAY_ID="Cairo-U00C10B122"

PRODUCT_BUILD_PROP_OVERRIDES += \
    TARGET_BUILD_FLAVOR="CRO-U00-$(TARGET_BUILD_VARIANT)"

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRIVATE_BUILD_DESC="CRO-U00-$(TARGET_BUILD_VARIANT) 6.0 HUAWEICRO-U00 1531390129 test-keys"

BUILD_FINGERPRINT := HUAWEI/CRO-U00/HWCRO-U6580M:6.0/HUAWEICRO-U00/C10B122:$(TARGET_BUILD_VARIANT)/test-keys

PRODUCT_GMS_CLIENTID_BASE := android-huawei
